### ISSUE TITLE
Fastq file URLs from DNAnexus fail without errors

### ISSUE THREAD

**Issue by MariaNattestad** [chmille4/taxonomer.iobio#28]
Thank you for the great tool! 

Taxonomer.iobio cannot read files through DNAnexus URLs despite working fine when those files are first downloaded to a computer and then uploaded to taxonomer.iobio through the UI. 

Here is a link to a file that will let you reproduce the issue:
https://dl.dnanex.us/F/D/Z9xgyB4X4QjJgbbYFGjXy5VVgkGGKj1y1Yj0xKb7/SRR905624.fastq​

There are no errors generated, only the "..." keeps going forever. I am unsure what the problem is, but in case it helps to identify the issue, I'll note that another web application fastq.bio can read those fastq file URLs successfully, so it may be helpful to compare against their codebase: https://github.com/robertaboukhalil/fastq.bio

Also, is there any way taxonomer.iobio could work on fastq.gz files? Most fastq files on DNAnexus are gzipped to save space, and it would be great to make it easy for our users to use taxonomer.iobio. 

Thank you for your help!

**Comment by chmille4** [comment]
Hi Maria

Thanks for bringing this to our attention. We will look into it.

In the mean time you can use taxonomer.com, which is a (somewhat) new site that the taxonomer folks (along with the help of the iobio team)  created. It's based on the original taxonomer.iobio site but has had some extra development. I just tested the dnanexus link and it works on that site. Also that site should support fastq.gz as well.

**Comment by MariaNattestad** [comment]
taxonomer.com looks great, thanks for passing that along. I can see that users need to sign up to use it, so would we be able to send users there through a simple link (and pass file URLs through parameters in the URL) like we can for the IOBIO viewers? 
Thanks for the great work!

**Comment by chmille4** [comment]
no, taxonomer.com isn't designed to support link-construction like iobio apps are, so users would have to copy the url and manually start the analysis.

What is your goal? Are you trying to integrate taxonomer.iobio into some other app?

**Comment by MariaNattestad** [comment]
I'm working at DNAnexus as of a few months ago, and we have these file viewers that allow users to visualize data. I made file viewers for bam iobio and vcf iobio that allow a user to choose a file and its index file, and then the viewer will just construct a URL with links to the chosen files. It makes it very easy for DNAnexus users to use these awesome tools. (If you ever get overloaded with traffic from DNAnexus, just let me know and we can figure out how to host our own copy of these tools.)
Now we are trying to add taxonomer.iobio too. I appreciate your help!

**Comment by chmille4** [comment]
Very cool, I just noticed a few weeks ago that bam.iobio and vcf.iobio were integrated into DNAnexus.  And as for traffic, we love traffic! Please send all you can.

I should be able to take a look into why taxonomer.iobio is failing with DNANexus links sometime this week and will update you when I know more.

**Comment by chmille4** [comment]
Ok, it was a simple fix. The test dnanexus url is working now
```
http://taxonomer.iobio.io/?url=https://dl.dnanex.us/F/D/Z9xgyB4X4QjJgbbYFGjXy5VVgkGGKj1y1Yj0xKb7/SRR905624.fastq
```

**Comment by MariaNattestad** [comment]
Excellent, thank you so much for the quick response!

**Comment by MariaNattestad** [comment]
By the way, where does this dataset come from and can we host a copy of it for demos and such?
https://s3.amazonaws.com/iobio/ebola_sample.fastq

**Comment by chmille4** [comment]
It comes from the SRA (link below), so yes it is free to use.

https://www.ncbi.nlm.nih.gov/sra/?term=SRR1553464

**Comment by MariaNattestad** [comment]
Thank you!

**Comment by MariaNattestad** [comment]
Hi Chase,

Unfortunately this problem has returned. Perhaps the code on the server reverted back to its old state before your fix.

The link above is no longer working, and here is a fresh link that is also failing:
http://taxonomer.iobio.io/?url=https://dl.dnanex.us/F/D/Yv9qyjb0bXF3Bv8Zk8kPyXZ2vfY09G99JGJY7Qb2/ebola_sample_for_taxonomer.iobio.fastq

I appreciate your help!

Maria

**Comment by chmille4** [comment]
Hi Maria, this slipped off my radar with Thanksgiving and travel. It should be working now. Let me know if you still see the issue.

**Comment by MariaNattestad** [comment]
Perfect, thank you!
